### ISSUE TITLE
How Do I Reorganize  the Folders

### ISSUE THREAD

**Issue by jidloyola** [CreArts-Community/Settings-Icons#10]
Hello. First off, you have an awesome Obsidian vault setup! My question is, how do I reorganize the folders and have them placed under specific folder headers?

**Comment by CorellanStoma** [comment]
Hi and Thank You! Well, This Issue page is for another project. 👀

You can, you create the issue there, there I can help you about the details:
https://github.com/CreArts-Community/CreArts-Obsidian/issues/new/choose
